### ISSUE TITLE
Error: Header must provide a Content-Length property.

### ISSUE THREAD

**Issue by patbenatar** [standardrb/vscode-standard-ruby#27]
Recently (last couple of days), saving with `editor.formatOnSave` enabled hangs indefinitely. Disabling standardrb extension fixes the saving issue. The "Extension Host (Remote)" log shows this stack trace from vscode-standard-ruby-0.0.16:

```
2024-06-28 16:22:15.616 [error] Error: Header must provide a Content-Length property.
    at Ms.onData (/root/.vscode-server-insiders/extensions/testdouble.vscode-standard-ruby-0.0.16/out/extension.js:2:19059)
    at Socket.<anonymous> (/root/.vscode-server-insiders/extensions/testdouble.vscode-standard-ruby-0.0.16/out/extension.js:2:18789)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Socket.Readable.push (node:internal/streams/readable:390:5)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
```

**Comment by searls** [comment]
Seems like a dupe of #26. Check that thread?
